defaultRounds: 1
defaultSpectators: true
spawn:
  x: 0
  y: 0
  z: 0
  world: "world"
  yaw: 0
  pitch: 0
  gamemode: "ADVENTURE"
arenasWorld:
  gamerules:
    doDaylightCycle: false
    doWeatherCycle: false
    announceAdvancements: false
    doMobSpawning: false
  time: 6000
  storm: false
  thundering: false
language: "en"
languages:
  en:
    youAreNotAPlayer: "§cYou need to be a player to run this command."
    noArgs: "§cNot enough args!"
    badArgs: "§cBad args!"
    noPerm: "§cYou don't have permission to run this command."
    alreadySentDuelRequest: "§cYou already sent a duel request to %player_name%"
    youAreInDuel: "§cYou can't run this command while you are in a duel."
    enemyIsInDuel: "§c%player_name% is in a duel."
    noDuelRequest: "§C%player_name% didn't send you any duel requests."
    noPlayer: "§c%player_name% is not online."
    cantDuelYourself: "§cYou can't send duel to yourself!"
    duelRequestGui:
      title: "§6Send duel request to §7%player_name%"
      glassName: " "
      contentGlassName: " "
      roundsName: "§fFirst to"
      spectatorsName: "§fEnable spectators"
    duelRequestAcceptButton: "[Accept]"
    duelRequestAcceptButtonHover: "§aClick to accept!"
    duelStart:
      countback: "§e%value%" # value = time left until start
      started: "§aBattle!"
    kit:
      created: "§aKit successfully created: %value%" # value = kit's name
      loaded: "§aKit loaded successfully: %value%" # value = kit's name
      deleted: "§aKit successfully deleted: %value%" # value = kit's name
data:
  kits: {}
  players: {}
  arenas: {}