defaultRounds: 1
defaultSpectators: true
spawn:
  x: 0
  y: 0
  z: 0
  world: "world"
  yaw: 0
  pitch: 0
  gamemode: "ADVENTURE"
arenasWorld:
  gamerules:
    doDaylightCycle: false
    doWeatherCycle: false
    announceAdvancements: false
    doMobSpawning: false
  time: 6000
  storm: false
  thundering: false
language: "en"
languages:
  en:
    youAreNotAPlayer: "§cYou need to be a player to run this command."
    noArgs: "§cNot enough args!"
    alreadySentDuelRequest: "§cYou already sent a duel request to %player_name%"
    youAreInDuel: "§cYou can't run this command while you are in a duel."
    enemyIsInDuel: "§c%player_name% is in a duel."
    noDuelRequest: "§C%player_name% didn't send you any duel requests."
    noPlayer: "§c%player_name% is not online."
    duelRequestGui:
      title: "§6Send duel request to §7%player_name%"
      glassName: " "
      contentGlassName: " "
      defaultRounds: "§fFirst To §6%value%"
      defaultSpectators: "§fSpectators: §6%value%"
    duelRequestAcceptButton: "[Accept]"
    duelRequestAcceptButtonHover: "§aClick to accept!"
data:
  kits:
  players:
  arenas: